version: "3.9"
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: clientvar
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      DATABASE_URL: "mysql://ptdhzopgyi8a0y606e92:pscale_pw_iwA8fLpzvEWxBxoCVXQ1r0QFPqt3GZpg9CLhnDupMRR@aws.connect.psdb.cloud/sklepszkola?sslaccept=strict"
      NEXTAUTH_SECRET: "huj"
      NEXTAUTH_URL: "http://localhost:3000/"
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      NODEMAILER_USER: "u19_nikodemgolawski@zsp1.siedlce.pl"
      NODEMAILER_PASSWORD: "nrvp doep bxkp fhhl"
